spring:
  application:
    name: auth-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-ip-address: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
firebase:
  config:
    path: serviceAccount.json
    api-key: AIzaSyD-7v1X2x4g0J6k3q8z5Y5Z5Y5Z5Y5Z5Y
    auth-url: https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword
server:
  port: 0