CREATE TABLE report (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT,
  description    TEXT,
  photo_url      TEXT,
  status         VARCHAR(50),
  created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  validated_at   TIMESTAMP WITHOUT TIME ZONE,
  latitude       NUMERIC(10,8),
  longitude      NUMERIC(11,8),
  category       VARCHAR(100),
  problem_type   VARCHAR(100),
  relevance      VARCHAR(100)
);
