spring:
  application:
    name: report-service

  config:
    import: optional:classpath:application-secrets.yml

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-ip-address: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}

server:
  port: 0

feign:
  client:
    config:
      image-service: http://localhost:8080/v1/images
      gamification-service: http://localhost:8081/v1/gamification
