spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/users/**
        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/v1/images/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/v1/auth/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/v1/reports/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-ip-address: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
server:
  port: 8080
