services:
  postgres_green:
    image: postgres:15
    container_name: postgres_green
    restart: always
    environment:
      POSTGRES_USER: green_admin
      POSTGRES_PASSWORD: '@greenpassword'
      POSTGRES_DB: green_db
    ports:
      - "55432:5432"
    volumes:
      - postgres_green_data:/var/lib/postgresql/data
    networks:
      - green-network

volumes:
  postgres_green_data:

networks:
  green-network:
    driver: bridge
