CREATE TABLE users (
    id             SERIAL PRIMARY KEY,
    name           VARCHAR(100) NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL,
    phone          VARCHAR(20) NOT NULL UNIQUE,
    email		   VARCHAR(100) NOT NULL UNIQUE,
    photo_url      VARCHAR(255),
    role           VARCHAR(50) NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    firebase_uid VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE `achievements` (
  `id`          INT(10)      NOT NULL AUTO_INCREMENT,
  `title`       VARCHAR(100) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`title`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `quests` (
  `id`          INT(10)      NOT NULL AUTO_INCREMENT,
  `title`       VARCHAR(100) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`title`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `achievements_progress` (
  `id`                   INT(10)      NOT NULL AUTO_INCREMENT,
  `achievementsid`       INT(10)      NOT NULL,
  `usersid`              INT(10)      NOT NULL,
  `completed_challenges` INT(10)      NULL,
  `status`               INT(20)      NULL,
  PRIMARY KEY (`id`),
  KEY `fk_ap_achievements` (`achievementsid`),
  KEY `fk_ap_users`        (`usersid`),
  CONSTRAINT `fk_ap_achievements`
    FOREIGN KEY (`achievementsid`) REFERENCES `achievements` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_ap_users`
    FOREIGN KEY (`usersid`) REFERENCES `users` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `achievements_quests` (
  `achievementsid` INT(10) NOT NULL,
  `questsid`       INT(10) NOT NULL,
  `goal`           INT(10) NOT NULL,
  KEY `fk_aq_achievements` (`achievementsid`),
  KEY `fk_aq_quests`       (`questsid`),
  CONSTRAINT `fk_aq_achievements`
    FOREIGN KEY (`achievementsid`) REFERENCES `achievements` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_aq_quests`
    FOREIGN KEY (`questsid`) REFERENCES `quests` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `quests_progress` (
  `id`       INT(10)      NOT NULL AUTO_INCREMENT,
  `questsid` INT(10)      NOT NULL,
  `usersid`  INT(10)      NOT NULL,
  `progress` INT(10)      NOT NULL,
  `status`   VARCHAR(20)  NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_qp_quests` (`questsid`),
  KEY `fk_qp_users`  (`usersid`),
  CONSTRAINT `fk_qp_quests`
    FOREIGN KEY (`questsid`) REFERENCES `quests` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_qp_users`
    FOREIGN KEY (`usersid`) REFERENCES `users` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE report (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT,
  description    TEXT,
  photo_url      TEXT,
  status         VARCHAR(50),
  created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  validated_at   TIMESTAMP WITHOUT TIME ZONE,
  latitude       NUMERIC(10,8),
  longitude      NUMERIC(11,8),
  category       VARCHAR(100),
  problem_type   VARCHAR(100)
);