spring:
  application:
    name: image-service

  config:
    import: optional:classpath:application-secrets.yml

  data:
    mongodb:
      uri: ${spring.data.mongodb.uri}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-ip-address: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}

app:
  gateway:
    base-url: http://localhost:8080

server:
  port: 0
