spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/green_db
    username: green_admin
    password: '@greenpassword'
    driver: org.postgresql.Driver
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-ip-address: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
server:
  port: 0
feign:
  client:
    config:
      image-service: http://localhost:8080/v1/images
      auth-service: http://localhost:8080/v1/auth